### ISSUE TITLE
Include configure webpage with workers

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#1]
Users should be able to configure the blocklists through serverless-dns deployment rather than rely on [rethinkdns.com/configure](https://rethinkdns.com/configure). Figure out a way to share code between the RethinkDNS website and serverless-dns deployment.

The domain name for the endpoint must be picked up automatically, if possible (should be, from within workers?).

**Comment by cyruz-git** [comment]
> > the resulting .mobileconfig file contains basic.rethinkdns.com as ServerURL.
> 
> That should be a quick fix.
> 
> Btw, does `.mobileconfig` even work? [celzero/rethink-app#580](https://github.com/celzero/rethink-app/issues/580)

Yes it does work when installing the mobileconfig as a profile after downloading it through Safari. I didn't check the app though.

**Comment by ignoramous** [comment]
> Related to this, when you deploy a Cloudflare worker and go to that worker configuration page, the resulting .mobileconfig file contains basic.rethinkdns.com as ServerURL.

Fixed. Pls see if the generated `mobileconfig` works now, as expected?

**Comment by cyruz-git** [comment]
> > Related to this, when you deploy a Cloudflare worker and go to that worker configuration page, the resulting .mobileconfig file contains basic.rethinkdns.com as ServerURL.
> 
> Fixed. Pls see if the generated `mobileconfig` works now, as expected?

I synced my repo but after the CF workflow run now I get this error when I try to open the webpage:

`TypeError: Failed to fetch; version: v70.0 (4). Please try after sometime.`

This is the query:

`configure?tstamp=2022/1667523717731&v=ext&u=https://mydomain&s=added`

**Comment by ignoramous** [comment]
> configure?tstamp=2022/1667523717731&v=ext&u=https://mydomain&s=added

We've moved to R2, but the "downloader" for the website still points to the older version which doesn't know about R2 at all... Moved the website to point to this new endpoint.

**Comment by cyruz-git** [comment]
Great, I confirm the mobileconfig points to the right server now.

**Comment by marcoclg19** [comment]
> Great, I confirm the mobileconfig points to the right server now.

I still have problems downloading the mobileconfig...
The file is downloaded as if it were a document and is not downloaded in such a way that I find mobileconfig in the DNS section in the iPhone settings.

**Comment by marcoclg19** [comment]
> > > Great, I confirm the mobileconfig points to the right server now.
> > 
> > 
> > I still have problems downloading the mobileconfig... The file is downloaded as if it were a document and is not downloaded in such a way that I find mobileconfig in the DNS section in the iPhone settings.
> 
> Download it with Safari, then open it with the Files app. After that, the profile needs to be installed from "Settings > General > VPN, DNS & Device Management".

Ops, now it works... please put this information on the website. Thank you very much again!

**Comment by Nxco1e** [comment]
We would like to work on this: 

> Users should be able to configure the blocklists through serverless-dns deployment rather than rely on [rethinkdns.com/configure](https://rethinkdns.com/configure). Figure out a way to share code between the RethinkDNS website and serverless-dns deployment.
> 
> The domain name for the endpoint must be picked up automatically, if possible (should be, from within workers?).

**Comment by madisontran16** [comment]
We are working on this issue.
-Madison and Nicole

**Comment by ignoramous** [comment]
This is a tough issue which requires specific know-how of the [Cloudflare Workers](https://developers.cloudflare.com/workers/static-assets/) platform to specifically host static pages. Let me know if you need any pointers at all. Feel free to `@` me or email me: `mz` at `celzero` dot `com`.

The page will need to built from a `filetag.json` which is versioned and the latest version is always available at `https://dl.rethinkdns.com/blocklists`. The webpage I built on top of that json is at https://rethinkdns.com/configure (it constructs a DNS-over-HTTPS "URL" or a DNS-over-TLS "subdomain" depending on the blocklists the end-user chooses: [see this screengrab](https://rethinkdns.com/img/screens/dns-blocklists.mp4)). The code for all of it is at https://github.com/celzero/website-dns (it is a private repository, but I'll share access with you two in the coming hours).
